# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

spring:
  # ThymeleafProperties
  thymeleaf:
    cache: false
  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

# Mybatis
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity  # 实体的包
  configuration:
    use-generated-keys: true  # 启用主键
    map-underscore-to-camel-case: true # user_info == userInfo

#  日志配置  使用logback-spring.xml 日志配置文件去设置吧
#logging:
#  level:
#    com.nowcoder.community: debug
#  file:
#    name: F:\javaweb\projectSpace\test.log